# Generated by Django 5.2.6 on 2025-09-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.IntegerField(default=0)),
                ("ename", models.CharField(max_length=50)),
                ("salary", models.IntegerField(default=0)),
            ],
        ),
    ]
