# Generated by Django 5.2.6 on 2025-09-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
