# Generated by Django 5.2.6 on 2025-09-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0002_delete_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("empid", models.IntegerField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=50)),
                ("salary", models.IntegerField(default=0)),
            ],
        ),
    ]
