# Generated by Django 5.2.6 on 2025-09-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="age",
            field=models.IntegerField(default=0),
        )
    ]
